includes:
  - https://github.ibm.com/cloud-docs/account
  - https://github.ibm.com/cloud-docs/billing-usage
  - https://github.ibm.com/cloud-docs/get-support
  - https://github.ibm.com/cloud-docs/cli
  